### ISSUE TITLE
Allow use with type annotations?

### ISSUE THREAD

**Issue by seanhess** [sweet-js/sweet-core#393]
I've been watching Sweet.js for a while. I love the project. Especially, I agree with the idea that our compile-to-js transformations should be composable. 

I've been a fan of strict types for a while, and right now type systems conflict with sweet's goals. A type system not only has to parse all the code, it has to understand all the code. This makes composable macros difficult, because the type system can't possibly know all the crazy things people will do with them. 

But the macro system itself doesn't have to understand all the code. 

Could we change sweet.js to allow the use of type annotations? I'm not saying it should understand them, or do anything with them, but _it shouldn't crash if it doesn't understand them_. Today, if I try to run sweet on a Typescript file, it crashes because it doesn't have a macro for the annotations. 

Today is it possible to define a pass-through for all Typescript-esque type annotations? The idea would be run run sweet.js first, then run the type checker on the resulting type-annotated code. If not could we change sweet so it doesn't die if it doesn't understand something? 

It's ironic that today sweet.js allows you to compose macros and transformations, but it isn't itself composable with any other transformation system. 

I think this is especially relevant given the announcement of Flow from facebook, and their choice to adopt Typescript-like annotations. My prediction is that developers will start to gravitate towards strict types within the next 3 years, and I would hate to see people have to choose between type safety and macros. 

Thoughts? I'm happy to help if I can. I have significant time to dedicate to making cool stuff like this happen.

**Comment by elibarzilay** [comment]
I know that this is old, but FWIW, re the Typed Racket mentions of @natefaubion, @BrendanEich:

It's wrong to say that a macro system should be tied to a type system -- and Typed Racket *is* a good example of that.  Yes, it's one big macro that does typechecking (and optimizations, even), but the very first step that it's doing is to completely expand the code so that it can typecheck just the core syntax.

Translated to sweet.js terms, it just needs to learn how to parse these JS-like languages and spit them out for the type tools to process.  It's obviously more than just a plain addition of stuff that it ignores, since types have identifiers, but if Flow and TypeScript have the same syntax, then there is just one JS-like language to deal with, even if the semantics implemented by the two type systems are different.

A very different issue is allowing the typechecker to interact with macros -- like allowing macros that expand differently based on the current type.  Something like this would be impossible with piping a checker behind a macro expander, but even Typed Racket doesn't have that.  -- It would require that TR implements its own macro expansion, with the additional type information injected in there.  (Or some way for the type checker to jump back to the macro generation, which I once tried via an ugly continuation hack...)
